[project]
name = "local-rlm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dspy-ai>=3.0.4",
    "google-generativeai>=0.8.6",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-timeout>=2.4.0",
]

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]
filterwarnings = [
    "ignore:Pydantic serializer warnings:UserWarning",
    "ignore:'asyncio.iscoroutinefunction' is deprecated:DeprecationWarning"
]

